# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MI_MEMORY_SYSFS) += mi_memory.o
mi_memory-y += mi_memory_sysfs.o
mi_memory-y += mi_ufs_info.o
mi_memory-y += mi_dram_info.o
mi_memory-y += mv.o
mi_memory-y += mi_mem_type.o
obj-y += mem_interface.o
