[CmdletBinding()]
param(
    [string]$BootImagePath = "",
    [string]$BuildLabel = "",
    [string]$KernelCommit = "",
    [string]$Outcome = "unknown",
    [string]$Note = "",
    [string]$OutputRoot = "",
    [switch]$NoZip
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptVersion = "1.0.0"
$SchemaVersion = 1

function Write-Step {
    param([string]$Message)
    Write-Host ("[Lisa-TWRP] " + $Message)
}

function Get-SafeName {
    param([string]$Value, [int]$MaxLength = 40)
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "unlabeled"
    }

    $safe = $Value -replace '[^A-Za-z0-9._-]+', '-'
    $safe = $safe.Trim('-', '.', '_')
    if ([string]::IsNullOrWhiteSpace($safe)) {
        $safe = "unlabeled"
    }
    if ($safe.Length -gt $MaxLength) {
        $safe = $safe.Substring(0, $MaxLength)
    }
    return $safe
}

function Invoke-AdbShellCapture {
    param(
        [string]$AdbPath,
        [string]$Command,
        [string]$OutFile
    )

    $header = @(
        ("command=adb shell " + $Command),
        ("captured_utc=" + (Get-Date).ToUniversalTime().ToString("o")),
        ""
    )

    try {
        $body = & $AdbPath shell $Command 2>&1
        $exitCode = $LASTEXITCODE
        @($header + @("exit_code=" + $exitCode, "") + $body) |
            Out-File -FilePath $OutFile -Encoding utf8
        return $exitCode
    }
    catch {
        @($header + @("capture_exception=" + $_.Exception.Message)) |
            Out-File -FilePath $OutFile -Encoding utf8
        return 255
    }
}

function Get-AdbShellText {
    param(
        [string]$AdbPath,
        [string]$Command
    )

    try {
        $result = & $AdbPath shell $Command 2>$null
        if ($null -eq $result) {
            return ""
        }
        return (($result | Out-String).Trim())
    }
    catch {
        return ""
    }
}

function Pull-AdbPathIfPresent {
    param(
        [string]$AdbPath,
        [string]$RemotePath,
        [string]$LocalPath,
        [string]$StatusFile
    )

    $probeCommand = "if [ -e '$RemotePath' ]; then echo PRESENT; else echo MISSING; fi"
    $probe = Get-AdbShellText -AdbPath $AdbPath -Command $probeCommand

    if ($probe -notmatch "PRESENT") {
        Add-Content -Path $StatusFile -Value ("MISSING " + $RemotePath)
        return $false
    }

    $parent = Split-Path -Parent $LocalPath
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    try {
        $pullOutput = & $AdbPath pull $RemotePath $LocalPath 2>&1
        $exitCode = $LASTEXITCODE
        Add-Content -Path $StatusFile -Value ("PULL exit=" + $exitCode + " remote=" + $RemotePath + " local=" + $LocalPath)
        if ($null -ne $pullOutput) {
            $pullOutput | Add-Content -Path $StatusFile
        }
        return ($exitCode -eq 0)
    }
    catch {
        Add-Content -Path $StatusFile -Value ("ERROR remote=" + $RemotePath + " message=" + $_.Exception.Message)
        return $false
    }
}

function Write-HistoryFiles {
    param(
        [string]$Root,
        [pscustomobject]$Record
    )

    $csvPath = Join-Path $Root "ITERATIONS.csv"
    $mdPath = Join-Path $Root "ITERATIONS.md"

    $rows = @()
    if (Test-Path -LiteralPath $csvPath) {
        try {
            $rows = @(Import-Csv -LiteralPath $csvPath)
        }
        catch {
            $backup = $csvPath + ".corrupt-" + (Get-Date -Format "yyyyMMdd-HHmmss")
            Copy-Item -LiteralPath $csvPath -Destination $backup -Force
            $rows = @()
        }
    }

    $rows = @($rows + $Record)
    $rows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

    $md = New-Object System.Collections.Generic.List[string]
    $md.Add("# Lisa TWRP log iterations")
    $md.Add("")
    $md.Add("Generated by scripts/collect_lisa_twrp_logs.ps1. Existing iterations are never intentionally overwritten.")
    $md.Add("")
    $md.Add("| Iteration | Local time | Build label | Boot SHA256 | Kernel commit | Outcome | Folder |")
    $md.Add("| --- | --- | --- | --- | --- | --- | --- |")

    foreach ($row in $rows) {
        $label = ([string]$row.BuildLabel).Replace("|", "/")
        $outcome = ([string]$row.Outcome).Replace("|", "/")
        $folder = ([string]$row.Folder).Replace("|", "/")
        $sha = [string]$row.BootSha256
        if ($sha.Length -gt 16) {
            $sha = $sha.Substring(0, 16) + "..."
        }
        $commit = [string]$row.KernelCommit
        if ($commit.Length -gt 12) {
            $commit = $commit.Substring(0, 12)
        }
        $md.Add("| " + $row.Iteration + " | " + $row.TimestampLocal + " | " + $label + " | " + $sha + " | " + $commit + " | " + $outcome + " | " + $folder + " |")
    }

    $md | Set-Content -LiteralPath $mdPath -Encoding UTF8
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptDir ".."))

if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = Join-Path $repoRoot "twrp_logs"
}
$OutputRoot = [System.IO.Path]::GetFullPath($OutputRoot)
New-Item -ItemType Directory -Force -Path $OutputRoot | Out-Null

if ([string]::IsNullOrWhiteSpace($BootImagePath)) {
    $cwdBoot = Join-Path (Get-Location).Path "boot.img"
    $repoBoot = Join-Path $repoRoot "boot.img"

    if (Test-Path -LiteralPath $cwdBoot) {
        $BootImagePath = $cwdBoot
    }
    elseif (Test-Path -LiteralPath $repoBoot) {
        $BootImagePath = $repoBoot
    }
}

$bootFile = "UNKNOWN"
$bootSha256 = "UNKNOWN"
$bootBytes = 0
$bootLastWriteUtc = "UNKNOWN"

if (-not [string]::IsNullOrWhiteSpace($BootImagePath)) {
    $BootImagePath = [System.IO.Path]::GetFullPath($BootImagePath)
    if (-not (Test-Path -LiteralPath $BootImagePath -PathType Leaf)) {
        throw "Boot image not found: $BootImagePath"
    }

    $bootInfo = Get-Item -LiteralPath $BootImagePath
    $bootFile = $bootInfo.Name
    $bootBytes = $bootInfo.Length
    $bootLastWriteUtc = $bootInfo.LastWriteTimeUtc.ToString("o")
    $bootSha256 = (Get-FileHash -LiteralPath $BootImagePath -Algorithm SHA256).Hash.ToLowerInvariant()
}
else {
    Write-Warning "No boot.img path was supplied or auto-detected. The package will still be created, but boot SHA256 will be UNKNOWN."
}

if ([string]::IsNullOrWhiteSpace($BuildLabel)) {
    if ($bootFile -ne "UNKNOWN") {
        $BuildLabel = [System.IO.Path]::GetFileNameWithoutExtension($bootFile)
    }
    else {
        $BuildLabel = "unlabeled"
    }
}

if ([string]::IsNullOrWhiteSpace($KernelCommit)) {
    $git = Get-Command git -ErrorAction SilentlyContinue
    if ($null -ne $git -and (Test-Path -LiteralPath (Join-Path $repoRoot ".git"))) {
        try {
            $candidate = (& $git.Source -C $repoRoot rev-parse HEAD 2>$null | Out-String).Trim()
            if ($candidate -match '^[0-9a-fA-F]{40}$') {
                $KernelCommit = $candidate.ToLowerInvariant()
            }
        }
        catch {
        }
    }
}
if ([string]::IsNullOrWhiteSpace($KernelCommit)) {
    $KernelCommit = "UNKNOWN"
}

$existingNumbers = @()
Get-ChildItem -LiteralPath $OutputRoot -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.Name -match '^iter-(\d{4,})_') {
        $existingNumbers += [int]$Matches[1]
    }
}
$nextNumber = 1
if ($existingNumbers.Count -gt 0) {
    $nextNumber = (($existingNumbers | Measure-Object -Maximum).Maximum + 1)
}

$iteration = "{0:D4}" -f $nextNumber
$timestampName = Get-Date -Format "yyyyMMdd-HHmmss"
$timestampLocal = (Get-Date).ToString("o")
$timestampUtc = (Get-Date).ToUniversalTime().ToString("o")
$shortHash = "nohash"
if ($bootSha256 -ne "UNKNOWN") {
    $shortHash = $bootSha256.Substring(0, 12)
}
$safeLabel = Get-SafeName -Value $BuildLabel
$folderName = "iter-" + $iteration + "_" + $timestampName + "_" + $safeLabel + "_" + $shortHash
$iterationDir = Join-Path $OutputRoot $folderName
$rawDir = Join-Path $iterationDir "raw"
$pulledDir = Join-Path $iterationDir "pulled"

New-Item -ItemType Directory -Force -Path $rawDir | Out-Null
New-Item -ItemType Directory -Force -Path $pulledDir | Out-Null

$adb = Get-Command adb -ErrorAction Stop
$adbPath = $adb.Source

Write-Step "Starting ADB and waiting for a TWRP/recovery device..."
& $adbPath start-server | Out-Null
& $adbPath wait-for-device
if ($LASTEXITCODE -ne 0) {
    throw "adb wait-for-device failed."
}

$state = (& $adbPath get-state 2>$null | Out-String).Trim()
if ($state -ne "device") {
    throw "ADB device state is '$state', expected 'device'."
}

$device = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.product.device"
$model = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.product.model"
$slot = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.boot.slot_suffix"
$bootMode = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.bootmode"
$bootReason = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.boot.bootreason"
$twrpVersion = Get-AdbShellText -AdbPath $adbPath -Command "getprop ro.twrp.version"

if ([string]::IsNullOrWhiteSpace($device)) { $device = "UNKNOWN" }
if ([string]::IsNullOrWhiteSpace($model)) { $model = "UNKNOWN" }
if ([string]::IsNullOrWhiteSpace($slot)) { $slot = "UNKNOWN" }
if ([string]::IsNullOrWhiteSpace($bootMode)) { $bootMode = "UNKNOWN" }
if ([string]::IsNullOrWhiteSpace($bootReason)) { $bootReason = "UNKNOWN" }
if ([string]::IsNullOrWhiteSpace($twrpVersion)) { $twrpVersion = "UNKNOWN" }

Write-Step ("Collecting iteration " + $iteration + " into " + $iterationDir)

$commands = @(
    @{ File = "01_identity.txt"; Command = "id; echo; uname -a; echo; cat /proc/version 2>/dev/null || true" },
    @{ File = "02_boot_properties.txt"; Command = "for p in ro.product.device ro.product.model ro.bootmode ro.boot.slot_suffix ro.boot.bootreason sys.boot.reason ro.boot.vbmeta.device_state ro.boot.verifiedbootstate ro.boot.flash.locked ro.twrp.version; do printf '%s=' ""$p""; getprop ""$p""; done" },
    @{ File = "03_proc_cmdline.txt"; Command = "cat /proc/cmdline 2>/dev/null || true" },
    @{ File = "04_proc_bootconfig.txt"; Command = "cat /proc/bootconfig 2>/dev/null || true" },
    @{ File = "05_mounts.txt"; Command = "cat /proc/mounts 2>/dev/null || mount" },
    @{ File = "06_df.txt"; Command = "df -h 2>/dev/null || df" },
    @{ File = "07_block_by_name.txt"; Command = "ls -la /dev/block/by-name 2>/dev/null || true; echo; ls -la /dev/block/bootdevice/by-name 2>/dev/null || true" },
    @{ File = "08_pstore_listing.txt"; Command = "ls -la /sys/fs/pstore 2>/dev/null || true" },
    @{ File = "09_pstore_contents.txt"; Command = "if [ -d /sys/fs/pstore ]; then for f in /sys/fs/pstore/*; do [ -f ""$f"" ] || continue; echo '===== '""$f""' ====='; cat ""$f""; echo; done; fi" },
    @{ File = "10_last_kmsg.txt"; Command = "if [ -r /proc/last_kmsg ]; then cat /proc/last_kmsg; else echo NO_PROC_LAST_KMSG; fi" },
    @{ File = "11_dmesg_recovery.txt"; Command = "dmesg 2>&1" },
    @{ File = "12_logcat_recovery.txt"; Command = "logcat -b all -d 2>&1 || true" },
    @{ File = "13_twrp_recovery_log.txt"; Command = "if [ -r /tmp/recovery.log ]; then cat /tmp/recovery.log; else echo NO_TMP_RECOVERY_LOG; fi" },
    @{ File = "14_cache_recovery_log.txt"; Command = "if [ -r /cache/recovery/log ]; then cat /cache/recovery/log; else echo NO_CACHE_RECOVERY_LOG; fi" },
    @{ File = "15_cache_recovery_last_log.txt"; Command = "if [ -r /cache/recovery/last_log ]; then cat /cache/recovery/last_log; else echo NO_CACHE_RECOVERY_LAST_LOG; fi" },
    @{ File = "16_boot_reason_sources.txt"; Command = "echo ro.boot.bootreason=$(getprop ro.boot.bootreason); echo sys.boot.reason=$(getprop sys.boot.reason); echo ro.bootmode=$(getprop ro.bootmode); echo ro.boot.slot_suffix=$(getprop ro.boot.slot_suffix); echo ro.boot.verifiedbootstate=$(getprop ro.boot.verifiedbootstate); echo ro.boot.vbmeta.device_state=$(getprop ro.boot.vbmeta.device_state)" },
    @{ File = "17_kernel_message_sources.txt"; Command = "for p in /sys/fs/pstore /data/vendor/ramoops /cache/recovery /tmp; do echo '===== '""$p""' ====='; ls -la ""$p"" 2>&1 || true; done" }
)

foreach ($entry in $commands) {
    $out = Join-Path $rawDir $entry.File
    Invoke-AdbShellCapture -AdbPath $adbPath -Command $entry.Command -OutFile $out | Out-Null
}

$getpropPath = Join-Path $rawDir "18_getprop_redacted.txt"
$getpropLines = & $adbPath shell getprop 2>&1
$redactedProps = foreach ($line in $getpropLines) {
    if ($line -match '^\[([^\]]*(serial|imei|meid|mac_address|bluetooth\.address)[^\]]*)\]:') {
        $key = $Matches[1]
        "[" + $key + "]: [[REDACTED]]"
    }
    else {
        $line
    }
}
$redactedProps | Out-File -LiteralPath $getpropPath -Encoding utf8

$pullStatus = Join-Path $rawDir "19_pull_status.txt"
"Lisa TWRP pull status" | Set-Content -LiteralPath $pullStatus -Encoding utf8
Pull-AdbPathIfPresent -AdbPath $adbPath -RemotePath "/sys/fs/pstore" -LocalPath (Join-Path $pulledDir "pstore") -StatusFile $pullStatus | Out-Null
Pull-AdbPathIfPresent -AdbPath $adbPath -RemotePath "/data/vendor/ramoops" -LocalPath (Join-Path $pulledDir "data_vendor_ramoops") -StatusFile $pullStatus | Out-Null
Pull-AdbPathIfPresent -AdbPath $adbPath -RemotePath "/tmp/recovery.log" -LocalPath (Join-Path $pulledDir "twrp_recovery.log") -StatusFile $pullStatus | Out-Null
Pull-AdbPathIfPresent -AdbPath $adbPath -RemotePath "/cache/recovery/log" -LocalPath (Join-Path $pulledDir "cache_recovery.log") -StatusFile $pullStatus | Out-Null
Pull-AdbPathIfPresent -AdbPath $adbPath -RemotePath "/cache/recovery/last_log" -LocalPath (Join-Path $pulledDir "cache_recovery_last_log") -StatusFile $pullStatus | Out-Null

$manifest = [ordered]@{
    schema_version = $SchemaVersion
    collector = [ordered]@{
        name = "Lisa TWRP failure log collector"
        script_version = $ScriptVersion
        script_path = $MyInvocation.MyCommand.Path
    }
    iteration = [ordered]@{
        number = $iteration
        folder = $folderName
        timestamp_local = $timestampLocal
        timestamp_utc = $timestampUtc
        outcome = $Outcome
        note = $Note
    }
    build = [ordered]@{
        label = $BuildLabel
        kernel_commit = $KernelCommit
        boot_image_file = $bootFile
        boot_image_path = $BootImagePath
        boot_image_sha256 = $bootSha256
        boot_image_bytes = $bootBytes
        boot_image_last_write_utc = $bootLastWriteUtc
    }
    device = [ordered]@{
        product_device = $device
        model = $model
        slot_suffix = $slot
        boot_mode = $bootMode
        boot_reason = $bootReason
        twrp_version = $twrpVersion
    }
    collection = [ordered]@{
        adb_state = $state
        pstore_present = (Test-Path -LiteralPath (Join-Path $pulledDir "pstore"))
        data_vendor_ramoops_present = (Test-Path -LiteralPath (Join-Path $pulledDir "data_vendor_ramoops"))
        proc_last_kmsg_marker_file = "raw/10_last_kmsg.txt"
        recovery_dmesg_file = "raw/11_dmesg_recovery.txt"
        twrp_log_file = "raw/13_twrp_recovery_log.txt"
    }
}

$manifestPath = Join-Path $iterationDir "manifest.json"
$manifest | ConvertTo-Json -Depth 8 | Out-File -LiteralPath $manifestPath -Encoding utf8

$summary = @(
    "Lisa TWRP failure-log package",
    "collector_version=$ScriptVersion",
    "iteration=$iteration",
    "timestamp_local=$timestampLocal",
    "timestamp_utc=$timestampUtc",
    "build_label=$BuildLabel",
    "kernel_commit=$KernelCommit",
    "boot_image_file=$bootFile",
    "boot_image_sha256=$bootSha256",
    "boot_image_bytes=$bootBytes",
    "device=$device",
    "model=$model",
    "slot_suffix=$slot",
    "boot_mode=$bootMode",
    "boot_reason=$bootReason",
    "twrp_version=$twrpVersion",
    "outcome=$Outcome",
    "note=$Note",
    "",
    "Primary failure evidence:",
    "1. pulled/pstore and raw/09_pstore_contents.txt",
    "2. raw/10_last_kmsg.txt",
    "3. pulled/data_vendor_ramoops",
    "4. raw/13_twrp_recovery_log.txt",
    "5. raw/11_dmesg_recovery.txt"
)
$summary | Set-Content -LiteralPath (Join-Path $iterationDir "SUMMARY.txt") -Encoding utf8

$zipName = "lisa-twrp-" + $folderName + ".zip"
$historyRecord = [pscustomobject][ordered]@{
    Iteration = $iteration
    TimestampLocal = $timestampLocal
    TimestampUtc = $timestampUtc
    BuildLabel = $BuildLabel
    BootFile = $bootFile
    BootSha256 = $bootSha256
    BootBytes = $bootBytes
    KernelCommit = $KernelCommit
    Outcome = $Outcome
    Device = $device
    Slot = $slot
    TwrpVersion = $twrpVersion
    Folder = $folderName
    Zip = $zipName
    Note = $Note
}
Write-HistoryFiles -Root $OutputRoot -Record $historyRecord

Copy-Item -LiteralPath (Join-Path $OutputRoot "ITERATIONS.csv") -Destination (Join-Path $iterationDir "ITERATIONS.csv") -Force
Copy-Item -LiteralPath (Join-Path $OutputRoot "ITERATIONS.md") -Destination (Join-Path $iterationDir "ITERATIONS.md") -Force

$hashLines = New-Object System.Collections.Generic.List[string]
Get-ChildItem -LiteralPath $iterationDir -File -Recurse | Sort-Object FullName | ForEach-Object {
    $relative = $_.FullName.Substring($iterationDir.Length).TrimStart('\', '/')
    $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    $hashLines.Add($hash + "  " + ($relative -replace '\\', '/'))
}
$hashLines | Set-Content -LiteralPath (Join-Path $iterationDir "SHA256SUMS.txt") -Encoding ascii

$zipPath = Join-Path $OutputRoot $zipName
$zipHash = "NOT_CREATED"

if (-not $NoZip) {
    if (Test-Path -LiteralPath $zipPath) {
        throw "Refusing to overwrite existing ZIP: $zipPath"
    }

    Write-Step "Creating upload ZIP..."
    Compress-Archive -Path (Join-Path $iterationDir "*") -DestinationPath $zipPath -CompressionLevel Optimal
    $zipHash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
    ($zipHash + "  " + $zipName) | Set-Content -LiteralPath ($zipPath + ".sha256") -Encoding ascii
}

$latest = @(
    "iteration=$iteration",
    "folder=$folderName",
    "zip=$zipName",
    "zip_sha256=$zipHash",
    "boot_sha256=$bootSha256",
    "kernel_commit=$KernelCommit",
    "timestamp_local=$timestampLocal",
    "outcome=$Outcome"
)
$latest | Set-Content -LiteralPath (Join-Path $OutputRoot "LATEST.txt") -Encoding utf8

Write-Host ""
Write-Host "=== Lisa TWRP collection complete ==="
Write-Host ("ITERATION      : " + $iteration)
Write-Host ("OUTPUT_DIR     : " + $iterationDir)
if (-not $NoZip) {
    Write-Host ("UPLOAD_THIS_ZIP: " + $zipPath)
    Write-Host ("ZIP_SHA256     : " + $zipHash)
}
Write-Host ("BOOT_SHA256    : " + $bootSha256)
Write-Host ("KERNEL_COMMIT  : " + $KernelCommit)
Write-Host ""
Write-Host "Upload the generated ZIP to ChatGPT. Keep the whole twrp_logs directory locally so older iterations remain retrievable."
